baseURL = "https://tamirr.xyz"
title = "TAMIRR"

[permalinks]
    post = "/blog/:slug"

[menu]

  [[menu.main]]
    name = "BIO"
    url = "/bio"
    weight = 10

  [[menu.main]]
    name = "BLOG"
    url = "/blog"
    weight = 10

  [[menu.main]]
    name = "MEDIA"
    url = "/media"
    weight = 20

  [[menu.main]]
    name = "USES"
    url = "/uses"
    weight = 30

  [[menu.main]]
    name = "LINKS"
    url = "/links"
    weight = 40

  [[menu.main]]
    name = "CONTACT"
    url = "/contact"
    weight = 50

  [[menu.social]]
    name = "YouTube"
    pre = "youtube"
    url = "https://youtube.com/@tamirrxyz"
    weight = 20

  [[menu.social]]
    name = "RSS Feed"
    pre = "rss"
    url = "/index.xml"
    weight = 30


[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.highlight]
    style = 'catppuccin-macchiato'
