baseURL = "https://tamirr.xyz/"
title = "TAMIRR"

[permalinks]
    post = "/blog/:slug"

[menu]

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 10

  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 10

  [[menu.main]]
    name = "Videos"
    url = "/videos"
    weight = 20

  [[menu.main]]
    name = "Uses"
    url = "/uses"
    weight = 30

  [[menu.main]]
    name = "Links"
    url = "/links"
    weight = 40

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 50

  [[menu.social]]
    name = "YouTube"
    pre = "youtube"
    url = "https://youtube.com/@tamirrxyz"
    weight = 20

  [[menu.social]]
    name = "RSS Feed"
    pre = "rss"
    url = "/index.xml"
    weight = 30


[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.highlight]
    style = 'catppuccin-macchiato'
